### ISSUE TITLE
Dependent project react-native-node no longer exists

### ISSUE THREAD

**Issue by aschrijver** [ssbc/react-native-scuttlebot#1]
Hi @staltz 

I was looking through the code and noticed that https://github.com/staltz/react-native-node no longer exists, yet this project still depends on it.
Am I correct that it requires installing Node on android (e.g. using Termux) to get this project to work?

**Comment by staltz** [comment]
Hi @aschrijver. That project is not yet on github, but it's on npm.

**Comment by aschrijver** [comment]
Ah, thx!
